# Generated by Django 4.2.1 on 2023-05-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gw_Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id_type",
                    models.SmallIntegerField(
                        choices=[(1, "National_id"), (2, "International_id")]
                    ),
                ),
                ("names", models.CharField(max_length=100)),
                ("last_names", models.CharField(max_length=100)),
                ("living_address", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("phone1", models.IntegerField()),
                ("phone2", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gw_Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="green_wheels_app.gw_person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gw_Main_Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="green_wheels_app.gw_person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gw_Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.SmallIntegerField(
                        choices=[(1, "Seller"), (2, "WorkshopBoss")]
                    ),
                ),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="green_wheels_app.gw_person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gw_Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="green_wheels_app.gw_person",
                    ),
                ),
            ],
        ),
    ]
