# Generated by Django 4.2.1 on 2023-05-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_wheels_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gw_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Vehicle_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Vehicle',
            fields=[
                ('plate', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('made_year', models.IntegerField()),
                ('base_price', models.FloatField()),
                ('guarantee_end_date', models.DateField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_vehicle_model')),
            ],
        ),
    ]
