# Generated by Django 4.2.1 on 2023-06-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("green_wheels_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gw_workshop",
            old_name="workshop_id",
            new_name="headquarter_id",
        ),
    ]
