# Generated by Django 4.2.1 on 2023-05-28 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('green_wheels_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gw_Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Allowed_Panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_panel')),
            ],
        ),
    ]
