# Generated by Django 4.2.1 on 2023-05-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_wheels_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gw_service_diagnosis_vehicle',
            name='mechanic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gw_service_diagnosis_vehicle',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
