# Generated by Django 4.2.1 on 2023-06-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_wheels_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gw_service_diagnosis_vehicle',
            name='date',
            field=models.DateField(),
        ),
    ]
