# Generated by Django 4.2.1 on 2023-06-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_wheels_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gw_negotation',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gw_negotation',
            name='final_sale_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gw_negotation',
            name='last_modification_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gw_negotation',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, 'cash'), (2, 'credit_card')], default=1, null=True),
        ),
    ]
