# Generated by Django 4.2.1 on 2023-05-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_wheels_app', '0002_gw_panel_gw_allowed_panels'),
    ]

    operations = [
        migrations.AddField(
            model_name='gw_admin',
            name='password_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gw_manager',
            name='password_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
