# Generated by Django 4.2.1 on 2023-05-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_wheels_app', '0002_gw_brand_gw_vehicle_model_gw_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gw_Concessionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('mechanic_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Headquarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Negotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modification_date', models.DateField()),
                ('final_sale_price', models.FloatField()),
                ('pay_method', models.SmallIntegerField(choices=[(1, 'cash'), (2, 'credit_cart')], default=1)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_client')),
                ('vehicle_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_headquarter')),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Vehicle_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('concessionaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_concessionaire')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_vehicle_model')),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Service_Repair_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic_id', models.CharField(max_length=100)),
                ('diagnosis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_diagnosis')),
                ('workshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Request_Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('attended', models.BooleanField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_service')),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Replacement_Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_vehicle_model')),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Replacement_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('replacement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_replacement_part')),
                ('workshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Needed_Replacemnt_Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('diagnosis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_diagnosis')),
                ('replacement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_replacement_part')),
            ],
        ),
        migrations.AddField(
            model_name='gw_concessionaire',
            name='headquarter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_headquarter'),
        ),
        migrations.CreateModel(
            name='Gw_Attended_Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_date', models.DateField()),
                ('finished_date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_employee')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_service')),
            ],
        ),
        migrations.CreateModel(
            name='Gw_Service_Sell_Vehicle',
            fields=[
                ('gw_service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='green_wheels_app.gw_service')),
                ('concessionaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_concessionaire')),
                ('negotation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_wheels_app.gw_negotation')),
            ],
            bases=('green_wheels_app.gw_service',),
        ),
    ]
