# Generated by Django 4.2.1 on 2023-05-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_wheels_app', '0003_gw_admin_password_email_gw_manager_password_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gw_admin',
            name='password_email',
        ),
        migrations.RemoveField(
            model_name='gw_manager',
            name='password_email',
        ),
    ]
