# Generated by Django 4.2.1 on 2023-05-22 23:45

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('green_wheels_app', '0004_remove_gw_vehicle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
