# Generated by Django 4.2.1 on 2023-05-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_wheels_app', '0005_clientsgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientsGroup',
        ),
    ]
