# Generated by Django 4.2.1 on 2023-05-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_wheels_app', '0007_mycustomgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gw_Needed_Replacemnt_Part',
            new_name='Gw_Needed_Replacement_Part',
        ),
    ]
