# Generated by Django 4.2.1 on 2023-05-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "green_wheels_app",
            "0008_rename_gw_needed_replacemnt_part_gw_needed_replacement_part",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyCustomGroup",
        ),
    ]
