# Generated by Django 4.2.1 on 2023-05-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_wheels_app', '0010_gw_diagnosis_mechanic_name_alter_gw_diagnosis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gw_diagnosis',
            name='mechanic_id',
            field=models.IntegerField(),
        ),
    ]
