# Generated by Django 4.2.1 on 2023-05-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=6)),
                ('model_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
